dubbo:
  registry:
    protocol: zookeeper
    address: 192.168.188.128:2181
  protocol:
    port: 20081
    name: dubbo
  application:
    name: myprovider
    qos-enable: false
  scan:
    base-packages: com.offcn.service
